name: Deploy Portfolio
on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Build da Imagem
        run: |
          # Apenas buildamos a imagem no Docker
          docker build -t gabrielsousa/home-page:latest .

      - name: Instalar Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configurar Contexto Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy no Rancher
        run: |
          # 1. Atualiza a imagem no deployment
          kubectl set image deployment/home-page home-page=gabrielsousa/home-page:latest -n home-page
          
          # 2. Mudamos a política para 'Never' para forçar o uso da imagem local
          kubectl patch deployment home-page -n home-page -p '{"spec":{"template":{"spec":{"containers":[{"name":"home-page","imagePullPolicy":"Never"}]}}}}'
          
          # 3. Força o reinício do Pod para ler a imagem nova
          kubectl rollout restart deployment/home-page -n home-page