name: Deploy Portfolio SSH
on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest # O runner 'servidor-ubuntu-dell' cuidará disso
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Deploy via SSH (Rsync)
        uses: https://github.com/AkihiroSuda/rsync-action@v1
        with:
          host: 192.168.15.200
          user: gabrielsousa
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          src: "./*"
          dest: "/home/gabrielsousa/home-page-data/"
          args: "-azP --delete --exclude '.git*' --exclude '.gitea*'"