name: Deploy Portfolio
on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Build da Imagem
        run: |
          # Buildando a imagem no servidor via Docker local do Runner
          docker build -t gabrielsousa/home-page:latest .

      - name: Instalar Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configurar Contexto Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy no Rancher
        run: |
          # Agora usando o nome exato: deployment=meu-site | container=meu-site
          kubectl set image deployment/meu-site meu-site=gabrielsousa/home-page:latest -n site-pessoal
          
          # Aguarda a atualização ser propagada nos Pods
          kubectl rollout status deployment/meu-site -n site-pessoal