name: Deploy Portfolio
on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Build da Imagem
        run: |
          # Buildando a imagem no Docker do servidor
          docker build -t gabrielsousa/home-page:latest .
          
          # PASSO CRUCIAL: Importa a imagem do Docker diretamente para o K3s (Containerd)
          # Isso faz o Kubernetes "enxergar" a imagem sem precisar da internet
          sudo k3s ctr images import <(docker save gabrielsousa/home-page:latest)

      - name: Instalar Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configurar Contexto Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy no Rancher
        run: |
          # 1. Aplica a nova imagem
          kubectl set image deployment/meu-site container-0=gabrielsousa/home-page:latest -n site-pessoal
          
          # 2. Força a política para usar a imagem que acabamos de importar
          kubectl patch deployment meu-site -n site-pessoal -p '{"spec":{"template":{"spec":{"containers":[{"name":"container-0","imagePullPolicy":"Never"}]}}}}'
          
          # 3. Aguarda o sucesso do rollout
          kubectl rollout status deployment/meu-site -n site-pessoal --timeout=60s