name: Deploy Portfolio
on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Build da Imagem
        run: |
          # Buildando e tagueando a imagem localmente
          docker build -t gabrielsousa/home-page:latest .

      - name: Instalar Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configurar Contexto Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy no Rancher
        run: |
        # Tentaremos atualizar o container pelo nome 'nginx', que é o padrão do Rancher
          kubectl set image deployment/meu-site nginx=gabrielsousa/home-page:latest -n site-pessoal
        
        # Caso o nome acima falhe, o comando abaixo descobre o nome do container e aplica a imagem automaticamente:
        # kubectl set image deployment/meu-site $(kubectl get deployment meu-site -n site-pessoal -o jsonpath='{.spec.template.spec.containers[0].name}')=gabrielsousa/home-page:latest -n site-pessoal
        
          kubectl rollout status deployment/meu-site -n site-pessoal