name: Deploy Portfolio
on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Login no Gitea Registry
        uses: docker/login-action@v2
        with:
          registry: gitea.gabrielbrsousa.dev
          username: admin
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Build and Push
        run: |
          # Buildando e enviando para o seu servidor
          docker build -t gitea.gabrielbrsousa.dev/gabrielsousa/home-page:latest .
          docker push gitea.gabrielbrsousa.dev/gabrielsousa/home-page:latest

      - name: Configurar Contexto Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy no K3s
        run: |
          # Força o Kubernetes a usar a imagem que acabamos de subir
          kubectl set image deployment/home-page home-page=gitea.gabrielbrsousa.dev/gabrielsousa/home-page:latest -n home-page
          kubectl rollout restart deployment/home-page -n home-page