name: Deploy Portfolio
on:
  push:
    branches: [ main ] # Evite deploy em qualquer push de branch

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          # Usamos o hash do commit para versionar, evitando o cache problemático do 'latest'
          docker build -t gabrielsousa/home-page:${{ github.sha }} .
          docker push gabrielsousa/home-page:${{ github.sha }}

      - name: Configurar Contexto Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy no Rancher (K3s)
        run: |
          # Atualiza para a imagem específica do commit. 
          # O Kubernetes detectará a mudança de tag e fará o rollout automaticamente.
          kubectl set image deployment/home-page home-page=gabrielsousa/home-page:${{ github.sha }} -n home-page
          
          # Verifica se o deploy foi bem sucedido
          kubectl rollout status deployment/home-page -n home-page