name: Deploy Portfolio
on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Build da Imagem
        run: |
          # Buildando a imagem localmente no servidor via Runner
          docker build -t gabrielsousa/home-page:latest .

      - name: Instalar Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configurar Contexto Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy no Rancher
        run: |
          # 1. Atualiza a imagem no deployment
          kubectl set image deployment/meu-site container-0=gabrielsousa/home-page:latest -n site-pessoal
          
          # 2. Força a política para NÃO buscar no Docker Hub se a imagem estiver local
          kubectl patch deployment meu-site -n site-pessoal -p '{"spec":{"template":{"spec":{"containers":[{"name":"container-0","imagePullPolicy":"IfNotPresent"}]}}}}'
          
          # 3. Aguarda o status (com timeout menor para não travar o pipeline)
          kubectl rollout status deployment/meu-site -n site-pessoal --timeout=60s